export type ProductType =
  | "phone"
  | "watch"
  | "audio"
  | "charger"
  | "wifi"
  | "stylus"
  | "adapter"
  | "screen";

export interface Product {
  id: number;
  brand: string;
  model: string;
  colors: string;
  ram: string | null;
  rom: string | null;
  price: number;
  discount: number;
  photoUrl: string;
  specsUrl: string;
  type: ProductType;
}

export const products: Product[] = [
  { id: 1,  brand: "Xiaomi",    model: "Redmi A5 128GB",                        colors: "Negro, Azul, Verde",             ram: "8GB",    rom: "128GB",  price: 96.89,   discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-15c-4g.jpg",                                                     specsUrl: "https://www.gsmarena.com/xiaomi_redmi_15c_4g-14005.php",                        type: "phone"   },
  { id: 2,  brand: "Xiaomi",    model: "Redmi 15C 256GB",                       colors: "Negro, Verde, Azul, Café",       ram: "8-16GB", rom: "256GB",  price: 159.99,  discount: 26, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-15c-4g.jpg",                                                     specsUrl: "https://www.gsmarena.com/xiaomi_redmi_15c_4g-14005.php",                        type: "phone"   },
  /* { id: 3,  brand: "Xiaomi",    model: "Redmi 15C 128GB",                       colors: "Verde Menta, Azul",              ram: "4GB",    rom: "128GB",  price: 146.74,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-a7-pro.jpg",                                                     specsUrl: "https://www.gsmarena.com/xiaomi_redmi_a7_pro-14019.php",                        type: "phone"   },
  { id: 4,  brand: "Xiaomi",    model: "Redmi A7 Pro 128GB",                    colors: "Negro",                          ram: "4GB",    rom: "128GB",  price: 134.99,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-4g.jpg",                                                 specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_14-13604.php",                       type: "phone"   },
  { id: 5,  brand: "Xiaomi",    model: "Redmi Note 14 4G 256GB",               colors: "Negro, Verde, Azul",             ram: "8GB",    rom: "256GB",  price: 232.99,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-14-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_14_pro-13567.php",                   type: "phone"   },
  { id: 6,  brand: "Xiaomi",    model: "Redmi Note 14 Pro 256GB",              colors: "Negro",                          ram: "8GB",    rom: "256GB",  price: 298.57,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-4g.jpg",                                                 specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_15_4g-14117.php",                    type: "phone"   },
  { id: 7,  brand: "Xiaomi",    model: "Redmi Note 15 4G 256GB",               colors: "Negro, Azul, Verde",             ram: "8GB",    rom: "256GB",  price: 249.95,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_15_pro-14028.php",                   type: "phone"   },
  { id: 8,  brand: "Xiaomi",    model: "Redmi Note 15 Pro 5G 256GB",           colors: "Negro",                          ram: "8GB",    rom: "256GB",  price: 372.99,  discount: 40, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_15_pro-14028.php",                   type: "phone"   },
  { id: 9,  brand: "Xiaomi",    model: "Redmi Note 15 Pro 5G 512GB",           colors: "Negro",                          ram: "8GB",    rom: "512GB",  price: 392.24,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-15-pro-plus.jpg",                                       specsUrl: "https://www.gsmarena.com/xiaomi_redmi_note_15_pro_plus-14029.php",              type: "phone"   },
  { id: 10, brand: "Xiaomi",    model: "Redmi Note 15 Pro+ 5G 512GB",          colors: "Negro, Café, Azul",              ram: "12GB",   rom: "512GB",  price: 519.71,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x7-pro.jpg",                                                     specsUrl: "https://www.gsmarena.com/xiaomi_poco_x7_pro-13582.php",                         type: "phone"   },
   */{ id: 11, brand: "Xiaomi",    model: "Poco X7 Pro 512GB",                    colors: "Negro",                          ram: "12GB",   rom: "512GB",  price: 487.06,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-17.jpg",                                                               specsUrl: "https://www.gsmarena.com/xiaomi_17-14220.php",                                   type: "phone"   },
  { id: 12, brand: "Xiaomi",    model: "Xiaomi 17 5G 512GB",                   colors: "Negro, Verde, Azul",             ram: "12GB",   rom: "512GB",  price: 1135.00, discount: 11, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-17.jpg",                                                               specsUrl: "https://www.gsmarena.com/xiaomi_17-14220.php",                                   type: "phone"   },
  { id: 13, brand: "Xiaomi",    model: "Xiaomi 17 Ultra 512GB",                colors: "Negro",                          ram: "16GB",   rom: "512GB",  price: 1568.00, discount: 11, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-17-ultra.jpg",                                                         specsUrl: "https://www.gsmarena.com/xiaomi_17_ultra-14221.php",                             type: "phone"   },
  { id: 14, brand: "Xiaomi",    model: "Watch S4 Smartwatch",                  colors: "Negro, Plata",                   ram: null,     rom: null,     price: 172.29,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-watch-s4.jpg",                                                         specsUrl: "https://www.gsmarena.com/xiaomi_watch_s4-12345.php",                             type: "watch"   },
  /* { id: 15, brand: "Xiaomi",    model: "Band 10 Smartband",                    colors: "Negro",                          ram: null,     rom: null,     price: 50.36,   discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-smart-band-10.jpg",                                                     specsUrl: "https://www.gsmarena.com/xiaomi_smart_band_10-12300.php",                       type: "watch"   },
  { id: 16, brand: "Samsung",   model: "Galaxy A06 128GB",                     colors: "Light Blue",                     ram: "4GB",    rom: "128GB",  price: 138.95,  discount: 0,  photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-2024.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_a06_(2024)-12511.php",                  type: "phone"   },
  { id: 17, brand: "Samsung",   model: "Galaxy A07 128GB",                     colors: "Negro",                          ram: "4GB",    rom: "128GB",  price: 137.57,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a07-2022.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_a07-11452.php",                         type: "phone"   },
  { id: 18, brand: "Samsung",   model: "Galaxy A16 4G 128GB",                  colors: "Negro",                          ram: "4GB",    rom: "128GB",  price: 153.33,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-4g-2024.jpg",                                         specsUrl: "https://www.gsmarena.com/samsung_galaxy_a16_4g_(2024)-12617.php",               type: "phone"   },
   */{ id: 19, brand: "Samsung",   model: "Galaxy A17 4G 128GB",                  colors: "Negro, Light Blue",              ram: "4GB",    rom: "128GB",  price: 189.22,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a17.jpg",                                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_a17-14230.php",                         type: "phone"   },
  //{ id: 20, brand: "Samsung",   model: "Galaxy A26 5G 256GB",                  colors: "Negro, Verde, Blanco",           ram: "8-16GB", rom: "256GB",  price: 317.48,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a26-5g.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_a26-13679.php",                         type: "phone"   },
  { id: 21, brand: "Samsung",   model: "Galaxy A36 5G 256GB",                  colors: "Negro, Blanco",                  ram: "8GB",    rom: "256GB",  price: 355.64,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a36.jpg",                                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_a36-13497.php",                         type: "phone"   },
  //{ id: 22, brand: "Samsung",   model: "Galaxy A56 5G 256GB",                  colors: "Rosa, Verde, Negro",             ram: "12GB",   rom: "256GB",  price: 447.33,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a56.jpg",                                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_a56-13603.php",                         type: "phone"   },
  //{ id: 23, brand: "Samsung",   model: "Galaxy S25 5G 256GB",                  colors: "Verde Claro, Navy",              ram: "12GB",   rom: "256GB",  price: 819.81,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25.jpg",                                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_s25-13610.php",                         type: "phone"   },
  { id: 24, brand: "Samsung",   model: "Galaxy S25 FE 5G 256GB",               colors: "Negro, Azul, Navy",              ram: "8GB",    rom: "256GB",  price: 778.37,  discount: 18, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-fe.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_s25_fe-13938.php",                      type: "phone"   },
  //{ id: 25, brand: "Samsung",   model: "Galaxy S25 Ultra 512GB",               colors: "Plateado, Titanium Negro",       ram: "12GB",   rom: "512GB",  price: 1247.00, discount: 15, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra.jpg",                                         specsUrl: "https://www.gsmarena.com/samsung_galaxy_s25_ultra-13322.php",                   type: "phone"   },
  { id: 26, brand: "Samsung",   model: "Galaxy Watch 8 40mm",                  colors: "Plata",                          ram: null,     rom: null,     price: 294.45,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch8.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_watch8-13997.php",                      type: "watch"   },
  { id: 27, brand: "Samsung",   model: "Galaxy Watch 8 44mm",                  colors: "Graphite Negro",                 ram: null,     rom: null,     price: 309.45,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch8.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_watch8-13997.php",                      type: "watch"   },
  /* { id: 28, brand: "Samsung",   model: "Galaxy Fit 3",                          colors: "Negro, Silver",                  ram: null,     rom: null,     price: 76.91,   discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-fit3.jpg",                                             specsUrl: "https://www.gsmarena.com/samsung_galaxy_fit3-12100.php",                        type: "watch"   },
  { id: 29, brand: "Samsung",   model: "Galaxy Buds 3 Pro",                    colors: "Plateado",                       ram: null,     rom: null,     price: 177.88,  discount: 43, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-buds3-pro.jpg",                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_buds3_pro-12530.php",                   type: "audio"   },
  { id: 30, brand: "Samsung",   model: "Galaxy Buds Core",                     colors: "Negro, Blanco",                  ram: null,     rom: null,     price: 48.34,   discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-buds-core.jpg",                                     specsUrl: "https://www.gsmarena.com/samsung_galaxy_buds_core-14145.php",                   type: "audio"   },
  { id: 31, brand: "Samsung",   model: "Cargador 45W + Cable USB-C",           colors: "Negro",                          ram: null,     rom: null,     price: 34.74,   discount: 38, photoUrl: "https://images.samsung.com/is/image/samsung/p6pim/levant/ep-t4510xbegww/gallery/levant-45w-power-adapter-ep-t4510-ep-t4510xbegww-thumb-537823657", specsUrl: "https://www.samsung.com/global/galaxy/galaxy-s/s-accessories/chargers/", type: "charger" },
   */{ id: 32, brand: "Infinix",   model: "Hot 60i 4GB 256GB",                    colors: "Negro, Verde",                   ram: "4GB",    rom: "256GB",  price: 168.88,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-60i.jpg",                                                     specsUrl: "https://www.gsmarena.com/infinix_hot_60i-13983.php",                             type: "phone"   },
  { id: 33, brand: "Infinix",   model: "Hot 60i 8GB 256GB",                    colors: "Negro, Plata, Azul, Morado",     ram: "8GB",    rom: "256GB",  price: 185.66,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-60i.jpg",                                                     specsUrl: "https://www.gsmarena.com/infinix_hot_60i-13983.php",                             type: "phone"   },
  { id: 34, brand: "Infinix",   model: "Hot 60 Pro 256GB",                     colors: "Negro",                          ram: "8GB",    rom: "256GB",  price: 220.89,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-60-pro.jpg",                                                 specsUrl: "https://www.gsmarena.com/infinix_hot_60_pro-14003.php",                         type: "phone"   },
  { id: 35, brand: "Infinix",   model: "Hot 60 Pro+ 256GB",                    colors: "Negro",                          ram: "8GB",    rom: "256GB",  price: 258.71,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-hot-60-pro-plus.jpg",                                         specsUrl: "https://www.gsmarena.com/infinix_hot_60_pro_plus-14004.php",                    type: "phone"   },
  /* { id: 36, brand: "Infinix",   model: "Note 50 Pro 256GB",                    colors: "Violeta",                        ram: "16GB",   rom: "256GB",  price: 296.98,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-note-50-pro-4g.jpg",                                         specsUrl: "https://www.gsmarena.com/infinix_note_50_pro-13700.php",                        type: "phone"   },
  { id: 37, brand: "Infinix",   model: "Note 60 AI 5G 256GB",                  colors: "Negro, Titanio",                 ram: "8+8GB",  rom: "256GB",  price: 332.19,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-note-60.jpg",                                                     specsUrl: "https://www.gsmarena.com/infinix_note_60-14350.php",                             type: "phone"   },
  { id: 38, brand: "Infinix",   model: "Note 60 Pro 256GB",                    colors: "Azul, Naranja, Titanium",        ram: "16GB",   rom: "256GB",  price: 404.98,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-note-60-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/infinix_note_60_pro-14351.php",                        type: "phone"   },
  { id: 39, brand: "Infinix",   model: "GT 30 5G 256GB",                       colors: "Negro, Verde",                   ram: "8GB",    rom: "256GB",  price: 299.69,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/infinix-gt-30-pro.jpg",                                                 specsUrl: "https://www.gsmarena.com/infinix_gt_30_pro-14200.php",                          type: "phone"   },
  { id: 40, brand: "Honor",     model: "X7d 256GB",                            colors: "Negro",                          ram: "16GB",   rom: "256GB",  price: 224.55,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/honor-x7d.jpg",                                                           specsUrl: "https://www.gsmarena.com/honor_x7d-13850.php",                                   type: "phone"   },
   */{ id: 41, brand: "Honor",     model: "X8d 256GB",                            colors: "Azul, Negro, Gris",              ram: "8GB",    rom: "256GB",  price: 339.71,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/honor-x8d.jpg",                                                           specsUrl: "https://www.gsmarena.com/honor_x8d-14100.php",                                   type: "phone"   },
  { id: 42, brand: "Honor",     model: "X8d 512GB",                            colors: "Azul, Negro, Gris",              ram: "8GB",    rom: "512GB",  price: 374.96,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/honor-x8d.jpg",                                                           specsUrl: "https://www.gsmarena.com/honor_x8d-14100.php",                                   type: "phone"   },
  /* { id: 43, brand: "Honor",     model: "Magic 8 Lite 5G 256GB",                colors: "Negro, Verde",                   ram: "8GB",    rom: "256GB",  price: 399.99,  discount: 38, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic8-lite-5g.jpg",                                         specsUrl: "https://www.gsmarena.com/honor_magic8_lite_5g-14341.php",                       type: "phone"   },
  { id: 44, brand: "Honor",     model: "Magic 8 Lite 512GB",                   colors: "Negro, Dorado, Verde",           ram: "8-16GB", rom: "512GB",  price: 463.99,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/honor-magic8-lite-5g.jpg",                                         specsUrl: "https://www.gsmarena.com/honor_magic8_lite_5g-14341.php",                       type: "phone"   },
  { id: 45, brand: "Tecno",     model: "Camon 40 Ultimate 256GB",              colors: "Blanco, Verde",                  ram: "8+8GB",  rom: "256GB",  price: 245.33,  discount: 24, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-40.jpg",                                                     specsUrl: "https://www.gsmarena.com/tecno_camon_40-13697.php",                             type: "phone"   },
   */{ id: 46, brand: "Tecno",     model: "Spark 30 Pro 256GB",                   colors: "Varios",                         ram: "8GB",    rom: "256GB",  price: 199.67,  discount: 25, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/tecno-spark-30-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/tecno_spark_30_pro-13750.php",                         type: "phone"   },
  { id: 47, brand: "Tecno",     model: "Camon 50 Pro 256GB",                   colors: "Negro, Verde, Titanio",          ram: "8GB",    rom: "256GB",  price: 332.45,  discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/tecno-camon-50-pro.jpg",                                             specsUrl: "https://www.gsmarena.com/tecno_camon_50_pro-14200.php",                         type: "phone"   },
 // { id: 48, brand: "Motorola",  model: "Moto G15 512GB",                       colors: "Gris, Verde",                    ram: "4GB",    rom: "512GB",  price: 204.31,  discount: 0,  photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g15.jpg",                                                 specsUrl: "https://www.gsmarena.com/motorola_moto_g15-13480.php",                          type: "phone"   },
  { id: 49, brand: "Apple",     model: "iPhone 17 256GB",                      colors: "Azul Neblina",                   ram: null,     rom: "256GB",  price: 1258.00, discount: 0,  photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17.jpg",                                                     specsUrl: "https://www.gsmarena.com/apple_iphone_17-12638.php",                             type: "phone"   },
 /*  { id: 50, brand: "Accesorios", model: "Repetidor WiFi Xiaomi AC1200 Ra75",   colors: "Blanco",                         ram: null,     rom: null,     price: 32.48,   discount: 39, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-range-extender-ac1200-ra75.jpg",                         specsUrl: "https://www.mi.com/global/product/mi-range-extender-ac1200",                    type: "wifi"    },
  { id: 51, brand: "Accesorios", model: "Repetidor WiFi Xiaomi AC1200 Dual Band", colors: "Blanco",                      ram: null,     rom: null,     price: 38.65,   discount: 14, photoUrl: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi-wifi-range-extender-ac1200.jpg",                     specsUrl: "https://www.mi.com/global/product/mi-range-extender-ac1200",                    type: "wifi"    },
  { id: 52, brand: "Accesorios", model: "Repetidor WiFi TP-Link 750Mbps",      colors: "Blanco",                         ram: null,     rom: null,     price: 28.91,   discount: 25, photoUrl: "https://static.tp-link.com/upload/product-overview/2022/202210/20221017/RE205.png",                   specsUrl: "https://www.tp-link.com/us/home-networking/range-extender/re205/",              type: "wifi"    },
  { id: 53, brand: "Accesorios", model: "Lápiz Óptico 3 en 1 Stylus",         colors: "Varios",                         ram: null,     rom: null,     price: 15.96,   discount: 20, photoUrl: "https://m.media-amazon.com/images/I/61OZJFQrWfL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=stylus+pen+3+in+1+universal+tablet",                 type: "stylus"  },
  { id: 54, brand: "Accesorios", model: "Lápiz Digital Capacitivo Universal",  colors: "Varios",                         ram: null,     rom: null,     price: 19.84,   discount: 24, photoUrl: "https://m.media-amazon.com/images/I/61a8-GHxVQL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=digital+capacitive+stylus+pen+universal",            type: "stylus"  },
  { id: 55, brand: "Accesorios", model: "Lápiz Óptico Magnético Capacitivo",   colors: "Varios",                         ram: null,     rom: null,     price: 24.71,   discount: 25, photoUrl: "https://m.media-amazon.com/images/I/61mnBx9BIOL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=magnetic+capacitive+stylus+pen+ipad",                type: "stylus"  },
  { id: 56, brand: "Accesorios", model: "Lápiz Digital Universal Android/Apple/Windows", colors: "Varios",              ram: null,     rom: null,     price: 27.19,   discount: 24, photoUrl: "https://m.media-amazon.com/images/I/71OGqpnKrFL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=universal+digital+stylus+pen+android+apple+windows", type: "stylus"  },
  { id: 57, brand: "Accesorios", model: "Lápiz Bluetooth Rechazo Palma iPad",  colors: "Varios",                         ram: null,     rom: null,     price: 39.51,   discount: 13, photoUrl: "https://m.media-amazon.com/images/I/51vWa-1MNKL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=bluetooth+stylus+pen+palm+rejection+ipad",           type: "stylus"  },
  { id: 58, brand: "Accesorios", model: "Lápiz con AI Inclinación Bluetooth iPad", colors: "Varios",                    ram: null,     rom: null,     price: 44.38,   discount: 24, photoUrl: "https://m.media-amazon.com/images/I/61Tf4BEXFKL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=ai+tilt+bluetooth+stylus+pen+ipad",                  type: "stylus"  },
  { id: 59, brand: "Accesorios", model: "Lápiz Digital Premium Universal",     colors: "Varios",                         ram: null,     rom: null,     price: 48.95,   discount: 0,  photoUrl: "https://m.media-amazon.com/images/I/61OZJFQrWfL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=premium+universal+stylus+pen",                        type: "stylus"  },
  { id: 60, brand: "Accesorios", model: "Auriculares TWS M10 Bluetooth",       colors: "Negro",                          ram: null,     rom: null,     price: 12.45,   discount: 0,  photoUrl: "https://m.media-amazon.com/images/I/51dEEJGKqXL._AC_SL1200_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=TWS+M10+bluetooth+earbuds",                          type: "audio"   },
  */ { id: 61, brand: "Accesorios", model: "Auriculares Over-Ear tipo AirPods Max", colors: "Negro",                        ram: null,     rom: null,     price: 39.09,   discount: 14, photoUrl: "https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=over+ear+headphones+airpods+max+compatible",         type: "audio"   },
  /* { id: 62, brand: "Accesorios", model: "Transmisor/Receptor Bluetooth 5.0 USB 3.5mm", colors: "Negro",                 ram: null,     rom: null,     price: 14.57,   discount: 14, photoUrl: "https://m.media-amazon.com/images/I/61R0mAGkooL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=bluetooth+transmitter+receiver+usb+3.5mm",           type: "audio"   },
  { id: 63, brand: "Accesorios", model: "Adaptador OTG 3en1 USB-C + MicroUSB", colors: "Negro",                         ram: null,     rom: null,     price: 5.55,    discount: 13, photoUrl: "https://m.media-amazon.com/images/I/61-cTJ3MTSL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=OTG+adapter+3+in+1+USB-C+micro+USB",                 type: "adapter" },
  { id: 64, brand: "Accesorios", model: "Mica Mate Textura Papel iPad Pro 13", colors: "Transparente",                   ram: null,     rom: null,     price: 16.34,   discount: 14, photoUrl: "https://m.media-amazon.com/images/I/71OhxPKAGSL._AC_SL1500_.jpg",                                         specsUrl: "https://www.amazon.com/s?k=paper+texture+screen+protector+ipad+pro+13",         type: "screen"  },
 */];

export const brands = ["Todos", "Xiaomi", "Samsung", "Infinix", "Honor", "Tecno", "Motorola", "Apple", "Accesorios"];

export function getTopOffers(n = 6): Product[] {
  return [...products]
    .filter((p) => p.discount > 0)
    .sort((a, b) => b.discount - a.discount)
    .slice(0, n);
}

export function originalPrice(price: number, discount: number): number | null {
  if (discount <= 0) return null;
  return price / (1 - discount / 100);
}

export function waLink(model: string): string {
  return `https://wa.me/593995093687?text=Hola%2C+me+interesa+el+${encodeURIComponent(model)}`;
}
